### PR TITLE
Migration to Next js #686

### PR DESCRIPTION
**Pull request by anubhav2102**
Migration to Next js fixing #686 

Screenshot 2023-03-31 135838
Screenshot 2023-03-31 135857

Major Changes:
1) File/folder structure
2) Google analytics into /lib/gta.js
3) Modification with react-plotly as per next.js docs.

### CODE REVIEW

**Comment by arunavabasu-03** [comment]
Ahh !! Great 👍

**Comment by arunavabasu-03** [comment]
can you make use of new `appdir` and page layout of next js 13 !!

**Review by arunavabasu-03 — COMMENTED** [review]
`test` is falling we need to fix that in the next js way !! Although all things are perfect !!

**Comment by anubhav2102** [comment]
Tests are working locally, implemented app dir for next.js 13, screenshots attached for reference. 
Tests are getting stuck on CI workflow maybe due to CI configurations as per the sources.
@arunavabasu-03 

Screenshot 2023-04-27 195339
Screenshot 2023-04-25 040339

**Comment by arunavabasu-03** [comment]
@anubhav2102 thanks for this PR , for now closing the PR , keep contributing !!

**Pull request closed without merging**
