### PR TITLE
🚀 responsive mobileview of radis app

### PR DESCRIPTION
**Pull request by arunavabasu-03**
This pull request is for the responsiveness of the. radis app, i use the breakpoint properties of the grid by MUI, so now the radis app is responsive so mobile users also use without any problems. it basically fixes the #362 .
Hey @suzil , @erwanp , please review the changes and give some feedbacks.😀

### CODE REVIEW

**Comment by arunavabasu-03** [comment]
Screenshots :

CleanShot 2022-04-10 at 20 29 11@2x copy
CleanShot 2022-04-10 at 20 29 11@2x

**Comment by erwanp** [comment]
Hello @arunavabasu-03 , are these screenshots with the new version ?

**Comment by arunavabasu-03** [comment]
ok, I add it so that it takes the full width.

**Comment by arunavabasu-03** [comment]
looking great, i implement that !!

**Comment by suzil** [comment]
Looking good! One last little tweak: the wavenumber inputs will go off on a new line at some viewports. You can see it in this recording:

https://user-images.githubusercontent.com/13723264/163026919-80dee97d-b75b-46bf-8dfd-c94f618a6e83.mov

I think this will fix it:
```diff
--- a/website/src/components/fields/WavenumberRangeSlider.tsx
+++ b/website/src/components/fields/WavenumberRangeSlider.tsx
@@ -97,10 +97,10 @@ export const WavenumberRangeSlider: React.FC<WavelengthRangeSliderProps> = ({
         Wavenumber range (cm⁻¹)
       </Typography>
       <Grid container spacing={2} alignItems="center">
-        <Grid item sm={12} lg={2}>
+        <Grid item xs={2}>
           {rangeInput(lowerRange, setLowerRange, "min-wavenumber-input")}
         </Grid>
-        <Grid item xs={12} sm={12} lg={5}>
+        <Grid item xs={8}>
           <Slider
             value={[
               lowerRange === "" ? minRange : lowerRange,
@@ -112,7 +112,7 @@ export const WavenumberRangeSlider: React.FC<WavelengthRangeSliderProps> = ({
             max={maxRange}
           />
         </Grid>
-        <Grid item sm={12} lg={2}>
+        <Grid item xs={2}>
           {rangeInput(upperRange, setUpperRange, "max-wavenumber-input")}
         </Grid>
       </Grid>
```

Before:
Screen Shot 2022-04-12 at 2 14 37 PM


After:
Screen Shot 2022-04-12 at 2 14 44 PM

We might also want to change view at the `sm` point instead of the `xs` point when looking at that recording: https://github.com/suzil/radis-app/blob/b3fbcc481ff20193024f1c4cf9955ccf0839b2d2/website/src/components/CalcSpectrum.tsx#L235 Please take a look at let me know if we should or shouldn't.

This is definitely an improvement though. Would you mind adjusting the wavenumber inputs to not go to new lines? Thank you!

**Review by suzil — APPROVED** [review]

**Pull request merged**
