### PR TITLE
Add support for overlaying spectra

### PR DESCRIPTION
**Pull request by suzil**
https://user-images.githubusercontent.com/13723264/187048092-1615a7eb-796c-4b19-b3b7-8034fe01a825.mov

(The missing ylabel has been fixed, don't want to re-demo it)

I've changed the UI slightly from the ticket to instead have:
- Create: plots the given spectra, replacing the existing plot
- Add: Adds a new spectra

Would a different UI be better?

I hope it's OK @arunavabasu-03 that I took this ticket 🙈 

Closes https://github.com/suzil/radis-app/issues/452

### CODE REVIEW

**Comment by erwanp** [comment]
@minouHub you'll love it

**Comment by suzil** [comment]
There's some issue with the species I still need to figure out (you'll notice duplicated labels), just noticed it

**Comment by erwanp** [comment]
This is a very game-changing feature ! From a physics point of view, it allows very interesting thing : 

- compare databases !   (therefore, maybe the database should be in the legend? We might be able to re-use @arunavabasu-03 's filename [Database, Molecule, Temperature, Pressure, etc. ] )
- also, compare interaction of spectra ; i.e. ; compute CO spectrum (1), compute a CO2 spectrum (2), and compare with the overlap of a CO+CO2 spectrum (3)    

I like the Add to Plot syntax rather than the originally suggested Clear button. I'd keep that. Maybe we could rename "Create Plot" to "New Plot" ?

**Comment by suzil** [comment]
Screen Shot 2022-08-27 at 6 43 05 PM
@erwanp how is this?

**Comment by suzil** [comment]
Fixed unit of pressure from atm to bar ^

**Comment by erwanp** [comment]
Nice and clear ! Can we add one comma after the database name in the label, not to read "Hitran Pressure" as one block?

**Comment by suzil** [comment]
Screen Shot 2022-08-27 at 7 03 57 PM
@erwanp updated to add that comma, anything else?

**Comment by erwanp** [comment]
LGTM

**Pull request merged**
