### PR TITLE
Adding tooltips

### LINKED ISSUE #184: Add tooltips ?
Now that we're adding some complex parameters ( ex : nonequilibrium #183 ) I may be helpful to provide some help and description with tooltips. 

There could be a small info box [i] instead of the current  'mandatory field' `*`  (which I don't think is necessary),  that would show the tooltip on hovering.

I can provide the descriptions and contents. 
Could these tooltips include clickable links ? (so we can refer to future lecture supports/tutorials on spectroscopy @dcmvdbekerom )

### PR DESCRIPTION
**Pull request by arunavabasu-03**
Hey @suzil, @erwanp I add a  tooltip in the Tags field,   please check this approach so I add it to all fields. 😀 
It fixes  #184 .

Screenshot 2022-04-14 at 7 27 16 PM

### CODE REVIEW

**Comment by erwanp** [comment]
(fixes #184)

**Comment by suzil** [comment]
Looks good @arunavabasu-03 👍

**Comment by arunavabasu-03** [comment]
Ok @suzil 😀

**Comment by suzil** [comment]
@erwanp thoughts on this?

https://user-images.githubusercontent.com/13723264/163593788-0c67047d-c41a-44c2-b91a-89492354c7aa.mov

I'm thinking that maybe it would be good to leave off the tooltip on the slider?

**Comment by arunavabasu-03** [comment]
Ok @suzil , I add the full names of TRot and TVib and also remove them from the slider .😀

**Comment by erwanp** [comment]
The implementation is working, and the result is good looking. 

However, the real question is : do we really need them ? 

Most of the fields are already explicit. The current interface is great because it's simple. It's great if we can keep it like that. 

@arunavabasu-03 you have a newer eye on the project and therefore detain part of the answer : which of the existing fields where not explicit enough and should get some tooltip details?

**Comment by arunavabasu-03** [comment]
@erwanp, what I think is that max and min fields must require the tooltips  😀 .

**Comment by erwanp** [comment]
Because the slider is not explicit enough?

**Pull request closed without merging**
