### PR TITLE
#573 - Add Dark Mode Feature

### PR DESCRIPTION
**Pull request by anubhav2102**
#573 fixes
Implemented Dark mode toggle feature.
Below attached screenshots of work:
Screenshot 2023-03-28 031244
Screenshot 2023-03-28 031341
Screenshot 2023-03-28 031429
Screenshot 2023-03-28 031503

### CODE REVIEW

**Comment by arunavabasu-03** [comment]
Great work @anubhav2102

**Review by arunavabasu-03 — APPROVED** [review]

**Comment by arunavabasu-03** [comment]
@anubhav2102 can just run `yarn lint` in the front end and push the code again !!

**Comment by anubhav2102** [comment]
> @anubhav2102 can just run `yarn lint` in the front end and push the code again , After that we can proceed with merge!!

I have done it and added the commits as required.

**Review by suzil — APPROVED** [review]
Looks great! Thank you very much.

**Comment by erwanp** [comment]
Hello @anubhav2102 , it works but the spectrum plot doesn't have the Dark mode, therefore removing the interest. Is it fixable ? 

image

**Pull request merged**
