### PR TITLE
Add download_hitemp files

### LINKED ISSUE #625: Download & set-up HITEMP files on server
Related to #85 , I think Radis-App can handle HITEMP. 
This would be a first, as currently [Spectraplot](https://www.spectraplot.com/) has this functionality but the algorithm there is not able to cope with many lines, hence it is very limited. 

If @suzil you confirm to me that the server is never restarted, then it's easy and it's a one shot action : 

- I already prepared files [download_hitemp.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp.py), [download_hitemp_CO2.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp_CO2.py), [download_hitemp_H2O.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp_H2O.py) which would only have to be uploaded and executed on the server
- all the rest is automatic
- (CO2 and H2O may take ~2-3 hrs total) 

Then we would only need to have a frontend/backend change similar to the #570 #562  improvement.

### PR DESCRIPTION
**Pull request by erwanp**
Fixes #625

### CODE REVIEW

**Review by suzil — APPROVED** [review]

**Comment by suzil** [comment]
Running the scripts now.

**Comment by erwanp** [comment]
Excellent, thank you !

**Comment by suzil** [comment]
All scripts run!

**Comment by erwanp** [comment]
Nice ! 
@arunavabasu-03 just so you know, HITEMP is ready so could be added similarly to how you added GEISA  https://github.com/suzil/radis-app/pull/570 
(keep it for next week, there are already a few things on the fire right now ! )

**Pull request merged**
